//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BD_STLSPEntities1 : DbContext
    {
        public BD_STLSPEntities1()
            : base("name=BD_STLSPEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<T_CategoriaFlujo> T_CategoriaFlujo { get; set; }
        public virtual DbSet<T_CategoriaSeñas> T_CategoriaSeñas { get; set; }
        public virtual DbSet<T_Flujo> T_Flujo { get; set; }
        public virtual DbSet<T_Herramienta> T_Herramienta { get; set; }
        public virtual DbSet<T_Perfil> T_Perfil { get; set; }
        public virtual DbSet<T_PerfilxPermiso> T_PerfilxPermiso { get; set; }
        public virtual DbSet<T_Permiso> T_Permiso { get; set; }
        public virtual DbSet<T_Persona> T_Persona { get; set; }
        public virtual DbSet<T_Secuencia> T_Secuencia { get; set; }
        public virtual DbSet<T_Señas> T_Señas { get; set; }
        public virtual DbSet<T_Usuario> T_Usuario { get; set; }
        public virtual DbSet<T_DetalleFlujo> T_DetalleFlujo { get; set; }
    }
}
