//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Persona
    {
        public int idPersona { get; set; }
        public string nombres { get; set; }
        public string apellidoP { get; set; }
        public string apellidoM { get; set; }
        public string nombresApoderado { get; set; }
        public string direccion { get; set; }
        public System.DateTime fechaNacimiento { get; set; }
        public string tipoDoc { get; set; }
        public Nullable<long> numeroDoc { get; set; }
        public string tipoDiscapacidad { get; set; }
        public Nullable<long> telefono { get; set; }
        public long celular { get; set; }
        public string distrito { get; set; }
        public int idUsuario { get; set; }
    
        public virtual T_Usuario T_Usuario { get; set; }
    }
}
